# Generated by Django 5.1.1 on 2024-09-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='file_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
