# Generated by Django 5.0.1 on 2024-01-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_ippis_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
