# Generated by Django 5.0.1 on 2024-01-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_department_customuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
