# Generated by Django 5.0.1 on 2024-01-26 21:33

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('staff_comment', models.TextField(blank=True, max_length=100, null=True)),
                ('supervisor_comment', models.TextField(blank=True, db_index=True, max_length=100, null=True)),
                ('hod_comment', models.TextField(blank=True, db_index=True, max_length=100, null=True)),
                ('appraisal_status', django_fsm.FSMField(choices=[('initiated', 'Initiated'), ('supervisor_review', 'Supervisor Review'), ('hod_review', 'HOD Review'), ('admin_review', 'Admin Review'), ('completed', 'Completed')], default='initiated', max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
