# Generated by Django 5.0.1 on 2024-01-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appraisal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor'), ('hod', 'HOD'), ('admin', 'Admin')], default='staff', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.unit'),
        ),
    ]
