# Generated by Django 5.0.1 on 2024-01-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_unit_customuser_role_customuser_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department'),
        ),
    ]
