# Generated by Django 5.0.1 on 2024-01-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_unit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.unit'),
        ),
    ]
