# Generated by Django 5.0.1 on 2024-01-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_appraisal_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
