# Generated by Django 5.0.1 on 2024-09-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_customuser_date_of_acting_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
