# Generated by Django 5.0.1 on 2024-09-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser_institution_customuser_qualification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
