# Generated by Django 5.0.1 on 2024-09-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_phone_no_customuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='hod_comment',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='staff_comment',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='supervisor_comment',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='activity_task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='communication_skills',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='countersigning_officer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='countersigning_officer_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='countersigning_officer_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_of_acting_appointment',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_of_birth',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_of_evaluation',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_of_first_appointment',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='date_of_present_appointment',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='designation',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='file_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='head_of_department_comments',
            field=models.TextField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='initiative_creativity',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='institution',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='ippis_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='job_knowledge',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='judgment',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='overall_assessment_of_performance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='qualification',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='qualification_award_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='quality_of_work',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='quantity_of_work',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='relationship_with_subordinates',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='relationship_with_supervisor',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='reliability',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='reporting_officer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='reporting_officer_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='reporting_officer_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='supervisor_comments',
            field=models.TextField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='training_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='training_program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='training_provider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='working_with_others',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='institution',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='qualification',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
