# Generated by Django 5.0.1 on 2024-09-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_name_appraisal_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
