# Generated by Django 5.0.1 on 2024-09-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_appraisal_appraisal_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
