# Generated by Django 5.0.1 on 2024-09-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_appraisal_appraisal_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_period',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], db_index=True, max_length=10, null=True),
        ),
    ]
