# Generated by Django 5.0.1 on 2024-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_appraisal_appraisal_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='q1_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='q2_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='q3_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='q4_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='activity_task',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_rating',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='comment',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='communication_skills',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='countersigning_officer',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='countersigning_officer_from_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='countersigning_officer_to_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='initiative_creativity',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='ippis_no',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='job_knowledge',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='judgment',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='overall_assessment_of_performance',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='quality_of_work',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='quantity_of_work',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='relationship_with_subordinates',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='relationship_with_supervisor',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='reliability',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='reporting_officer',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='reporting_officer_from_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='reporting_officer_to_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='working_with_others',
            field=models.IntegerField(blank=True, choices=[(5, '5 - Excellent'), (4, '4 - Outstanding'), (3, '3 - Satisfactory'), (2, '2 - Needs improvement'), (1, '1 - Unacceptable')], db_index=True, null=True),
        ),
    ]
