# Generated by Django 5.0.1 on 2024-09-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_appraisal_q1_rating_appraisal_q2_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='appraisal_rating',
            new_name='q1_appraisal_rating',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='q1_rating',
            new_name='q2_appraisal_rating',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='q2_rating',
            new_name='q3_appraisal_rating',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='q3_rating',
            new_name='q4_appraisal_rating',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='q4_rating',
            new_name='total_appraisal_rating',
        ),
    ]
