# Generated by Django 5.0.1 on 2024-09-17 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_appraisal_rating_appraisal_q1_appraisal_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='date_submitted',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ippis_no',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
