# Generated by Django 5.0.1 on 2024-09-19 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_appraisal_date_submitted_alter_customuser_ippis_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='activity_task',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='overall_assessment_of_performance',
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_task', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('overall_assessment_of_performance', models.TextField(blank=True, db_index=True, null=True)),
                ('comment', models.TextField(blank=True, db_index=True, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to='app.appraisal')),
            ],
        ),
    ]
