# Generated by Django 5.0.1 on 2024-09-20 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_appraisal_activity_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='q1_appraisal_rating',
            new_name='appraisal_rating',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='date_of_evaluation',
            new_name='head_of_department_date_of_evaluation',
        ),
        migrations.RenameField(
            model_name='appraisal',
            old_name='date_submitted',
            new_name='staff_evaluation_date_submitted',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='appraisal_period',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='q2_appraisal_rating',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='q3_appraisal_rating',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='q4_appraisal_rating',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='training_location',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='training_program',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='training_provider',
        ),
        migrations.RemoveField(
            model_name='jobdescription',
            name='comment',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='accommplishments_since_last_evaluation',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='adhoc_duties_impact_real_duties',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='adhoc_duties_performed',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='capacity_development_since_last_evaluation',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='commendation_for_outstanding_performance',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='cost_project_assignment_responsibility_allowances',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='decision_making',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='details_of_commendation_for_outstanding_performance',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='details_sanction_discipline',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='difficulties_achieving_target',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='directing_and_controlling',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='joint_discussion_with_supervisor',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='main_duties_performed_by_staff',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='main_duties_performed_by_staff_from_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='main_duties_performed_by_staff_to_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='method_by_supervisor_to_resolve_difficulties',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='missed_opportunities_reason',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='overall_performance_assessment',
            field=models.CharField(choices=[('Outstanding', 'A - Outstanding'), ('Very Good', 'B - Very Good'), ('Good', 'C - Good'), ('fair', 'D - Fair'), ('Poor', 'E - Poor'), ('Very Poor', 'F - Very Poor')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='performance_measure_upto_standard_after_review',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='period_of_evaluation_from_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='period_of_evaluation_to_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='planning_and_organizing',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='project_assigment_completion_time',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY'), ('YEARLY', 'YEARLY')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisal',
            name='project_assignment_responsibility_capital_cost',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='project_assignment_responsibility_overhead_cost',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='project_quality_conformity_to_standard',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='project_quantity_conformity_to_standard',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='promotability',
            field=models.CharField(choices=[('Outstanding', 'A - Outstanding'), ('Very Good', 'B - Very Good'), ('Good', 'C - Good'), ('fair', 'D - Fair'), ('Poor', 'E - Poor'), ('Very Poor', 'F - Very Poor')], default='Good', max_length=20),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='sanction_discipline',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='skills_gap_requiring_improvement',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='staff_professionally_equipped',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='suggestions_that_contributed_to_changes',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='supervisor_date_of_evaluation',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='target_review_with_supervisor',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=5),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='training_requirements_to_handle_responsibilities',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='communication_skills',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='initiative_creativity',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='job_knowledge',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='judgment',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='quality_of_work',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='quantity_of_work',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='relationship_with_subordinates',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='relationship_with_supervisor',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='reliability',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='supervisor_comments',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='working_with_others',
            field=models.IntegerField(blank=True, choices=[(16, '5 - Excellent'), (13, '4 - Outstanding'), (10, '3 - Satisfactory'), (7, '2 - Needs improvement'), (5, '1 - Unacceptable')], db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='TrainingCourseSeminars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_program_type', models.TextField(blank=True, db_index=True, null=True)),
                ('training_location', models.TextField(blank=True, db_index=True, null=True)),
                ('training_from_date', models.DateField(blank=True, db_index=True, null=True)),
                ('training_to_date', models.DateField(blank=True, db_index=True, null=True)),
                ('appraisal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_course_seminars', to='app.appraisal')),
            ],
        ),
    ]
