# Generated by Django 5.0.1 on 2024-09-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_appraisal_commendation_for_outstanding_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='adhoc_duties_impact_real_duties',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='joint_discussion_with_supervisor',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='performance_measure_upto_standard_after_review',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='project_quality_conformity_to_standard',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='project_quantity_conformity_to_standard',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='staff_professionally_equipped',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, default='no', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='target_review_with_supervisor',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, default='no', max_length=5, null=True),
        ),
    ]
