# Generated by Django 5.0.1 on 2024-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_appraisal_adhoc_duties_impact_real_duties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='adhoc_duties_impact_real_duties',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='commendation_for_outstanding_performance',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='joint_discussion_with_supervisor',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='overall_performance_assessment',
            field=models.CharField(blank=True, choices=[('Outstanding', 'A - Outstanding'), ('Very Good', 'B - Very Good'), ('Good', 'C - Good'), ('fair', 'D - Fair'), ('Poor', 'E - Poor'), ('Very Poor', 'F - Very Poor')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='performance_measure_upto_standard_after_review',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='project_quality_conformity_to_standard',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='project_quantity_conformity_to_standard',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='promotability',
            field=models.CharField(blank=True, choices=[('Outstanding', 'A - Outstanding'), ('Very Good', 'B - Very Good'), ('Good', 'C - Good'), ('fair', 'D - Fair'), ('Poor', 'E - Poor'), ('Very Poor', 'F - Very Poor')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='sanction_discipline',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='staff_professionally_equipped',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='suggestions_that_contributed_to_changes',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='target_review_with_supervisor',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], db_index=True, max_length=5, null=True),
        ),
    ]
