# Generated by Django 5.0.1 on 2024-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_appraisal_adhoc_duties_impact_real_duties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='ippis_no',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
