# Generated by Django 5.0.1 on 2024-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_appraisal_ippis_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='commendation_for_outstanding_performance',
            field=models.IntegerField(blank=True, choices=[(2, 'yes'), (0, 'no')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='suggestions_that_contributed_to_changes',
            field=models.IntegerField(blank=True, choices=[(2, 'yes'), (0, 'no')], db_index=True, null=True),
        ),
    ]
