# Generated by Django 5.1.1 on 2024-09-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_appraisal_commendation_for_outstanding_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_type',
            field=models.CharField(choices=[('staff', 'Staff'), ('supervisor', 'Supervisor')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
